### ISSUE TITLE
Node-webkit download moved: breaks build process.

### ISSUE THREAD

**Issue by bbaumgar** [mllrsohn/grunt-node-webkit-builder#127]
`Fatal error: unable to download nodewebkit.`, occurs on a clean build, due to the rename from `node-webkit` to `nwjs`. Download links have been moved to the domain nwjs.io and have gone a slight naming change. 

For example, 
`http://dl.node-webkit.org/v0.12.0-alpha1/node-webkit-v0.12.0-alpha1-osx-x64.zip`
is now available at
`http://dl.nwjs.io/v0.12.0-alpha1/nwjs-v0.12.0-alpha1-osx-x64.zip`

**Comment by s2young** [comment]
+1

**Comment by bbaumgar** [comment]
There's now a PR in node-webkit-builder to fix this. I believe that if it lands, this project will work again.
https://github.com/mllrsohn/node-webkit-builder/pull/158

**Comment by gyzerok** [comment]
+1

**Comment by jeanres** [comment]
+1

**Comment by TasukuUno** [comment]
+1

**Comment by jkernech** [comment]
+1

**Comment by trevorah** [comment]
In the meantime, a temporary fix is to run the builder with the `downloadUrl` option set to `http://dl.nwjs.io/`. This will only work for versions pre 0.12.0.

**Comment by trevorah** [comment]
I've just done a release of node-webkit-builder@1.0.5 that fixes all node-webkit builds pre 0.12.0. This means if you do a fresh npm install, then the grunt-node-webkit-builder should pull in the fix.

For those that are building 0.12.0-alpha1, you can follow the status of the pending fix at https://github.com/mllrsohn/node-webkit-builder/issues/157.

**Comment by CoreyClarkPhD** [comment]
@trevorah for 0.12.0-alpha1 you also have to change the versionNameTemplate, I didn't realize that my PR would break all older builds until after I submitted it though.  The older builds still use node-webkit in file name, while all newer builds use nwjs, since the platform.js file is just returning a property there will have to be a little more work done on how to manage both of these naming conventions.

@bbaumgar I doubt my PR will land, since it will break all previous revisions (due to reason above), but you can clone the repo at https://github.com/CoreyClarkPhD/node-webkit-builder and replace the lib/index.js and lib/platform.js to get working with the latest release of nwjs.

**Comment by adam-lynch** [comment]
I guess just to be safe, run `npm cache clean` before installing again.

**Comment by sergiovilar** [comment]
+1

**Comment by trevorah** [comment]
@CoreyClarkPhD thanks for the tip!

node-webkit-builder@1.0.6 is now out with the fix to support nw.js v0.12.0-alpha1. Again, if you do a fresh npm install, then the grunt-node-webkit-builder should pull in the fix.

**Comment by vrunoa** [comment]
+1

**Comment by tarun1188** [comment]
+1

**Comment by anand-seeenivasagam** [comment]
+1

**Comment by senorcris** [comment]
+1

**Comment by ABeltramo** [comment]
Temporary fix: use a node-webkit version prior to 0.13
I put:
version: "0.12.1"

**Comment by Karlheinzniebuhr** [comment]
+1
